blueprint:
  name: HASP button to trigger a scene
  description: Create a button on the HASP to trigger a scene
  domain: automation
  input:
    hasp_name:
      name: HASP Device
      description: "Select the HASP device"
      selector:
        device:
          manufacturer: "HASwitchPlate"
          model: "HASP v1.0.0"
    hasp_page:
      name: HASP Page
      description: "Select the HASP page (1-11) for this scene button"
      selector:
        number:
          min: 1
          max: 11
          mode: box
    hasp_button:
      name: HASP Button
      description: "Select the HASP button for this scene"
      selector:
        number:
          min: 1
          max: 15
          mode: box
    hasp_scene:
      name: Scene to trigger
      description: "Select a scene for this button to trigger"
      selector:
        entity:
          domain: scene
    hasp_label:
      name: HASP Button Label
      description: "Enter text to appear on the button"
    hasp_font:
      name: HASP Button Font
      description: "Select the text font for this button label"
      selector:
        number:
          min: 0
          max: 10
          mode: slider

mode: restart
max_exceeded: silent

variables:
  haspname: !input hasp_name
  hasppage: !input hasp_page
  haspbutton: !input hasp_button

trigger:
  - platform: mqtt
    topic: "hasp/+/state/json"

condition: '{{ (trigger.payload_json.event == "p[" + hasppage + "].b[" + haspbutton + "]") and trigger.payload_json.value == "ON" }}'

action:
  - service: scene.turn_on
    entity_id: !input hasp_scene
  - service: mqtt.publish
    data:
      topic: "debug"
      payload_template: 'haspname: {{haspname}}'